# This formula is generated by scripts/update-homebrew-formula.sh.
# Canonical source: Bare-Systems/Tardigrade packaging/homebrew/tardigrade.rb

class Tardigrade < Formula
  desc "Small Zig edge server for static file serving, reverse proxying, and TLS termination"
  homepage "https://github.com/Bare-Systems/Tardigrade"
  version "0.6.3"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/Bare-Systems/Tardigrade/releases/download/v0.6.3/tardigrade-darwin-arm64.tar.gz"
      sha256 "507b741358f20ab5a45e2442e594b664a16a17dc247c711b21d76d36e47a440a"
    end
    on_intel do
      url "https://github.com/Bare-Systems/Tardigrade/releases/download/v0.6.3/tardigrade-darwin-x86_64.tar.gz"
      sha256 "4caa11a627aeda75ffb256ae557d2faf027a343408b32aeb8dc1f16dda60d7cd"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/Bare-Systems/Tardigrade/releases/download/v0.6.3/tardigrade-linux-aarch64.tar.gz"
      sha256 "84e3415e9647bd03dc1c16026853d8671487fb61286867d0eae4bb1f60294902"
    end

    on_intel do
      url "https://github.com/Bare-Systems/Tardigrade/releases/download/v0.6.3/tardigrade-linux-x86_64.tar.gz"
      sha256 "8445df63584ca2a6343574e77176c83e651ff81fe7b3a4b1d54443446a664fc3"
    end
  end

  def install
    bin.install "tardi"
    bin.install_symlink "tardi" => "tardigrade"
  end

  test do
    output = shell_output("#{bin}/tardi version")
    assert_match version.to_s, output
    assert_match "tls-profile=general", output
    assert_match "tls-backend=native", output
    assert_equal (bin/"tardi").realpath, (bin/"tardigrade").realpath
  end
end
