# This formula is generated by scripts/update-homebrew-formula.sh.
# Canonical source: Bare-Systems/Tardigrade packaging/homebrew/tardigrade.rb

class Tardigrade < Formula
  desc "Small Zig edge server for static file serving, reverse proxying, and TLS termination"
  homepage "https://github.com/Bare-Systems/Tardigrade"
  version "0.6.2"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/Bare-Systems/Tardigrade/releases/download/v0.6.2/tardigrade-darwin-arm64.tar.gz"
      sha256 "bb7fef4507809a5da3bb99d92876520c78ef43382c373fbe90b1c19d09db8cfa"
    end
    on_intel do
      url "https://github.com/Bare-Systems/Tardigrade/releases/download/v0.6.2/tardigrade-darwin-x86_64.tar.gz"
      sha256 "487c710daac951a22a657614c9fea419ef5e1ad7978af36c18646b041bd0596a"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/Bare-Systems/Tardigrade/releases/download/v0.6.2/tardigrade-linux-aarch64.tar.gz"
      sha256 "53eb30986d5b951f870dee2985755c4df82cc4eb45d9ee89c5e8ee771a4e0d64"
    end

    on_intel do
      url "https://github.com/Bare-Systems/Tardigrade/releases/download/v0.6.2/tardigrade-linux-x86_64.tar.gz"
      sha256 "2f98ed94aaf9caf652d4add7045bc446e6056b07845387dd0b3e0f3d919c2a03"
    end
  end

  def install
    bin.install "tardi"
    bin.install_symlink "tardi" => "tardigrade"
  end

  test do
    output = shell_output("#{bin}/tardi version")
    assert_match version.to_s, output
    assert_match "tls-profile=general", output
    assert_match "tls-backend=native", output
    assert_equal (bin/"tardi").realpath, (bin/"tardigrade").realpath
  end
end
